import Navbar from "../components/Navbar";

const Term = () => {
  return (
    <div className="flex flex-col">
      <Navbar showoptions={false} />
      <div className="min-h-screen bg-gray-50 py-10 px-4">
        <div className="max-w-4xl mx-auto bg-white rounded-2xl shadow-md p-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-6">
            Terms & Conditions
          </h1>

          <div className="text-gray-700 leading-relaxed space-y-6">
            <p>
              This document is an electronic record in terms of the Information
              Technology Act, 2000 and rules thereunder as applicable, including
              amended provisions pertaining to electronic records. This
              electronic record is generated by a computer system and does not
              require any physical or digital signatures. It is published in
              accordance with Rule 3(1) of the Information Technology
              (Intermediaries Guidelines) Rules, 2011, which require publishing
              the rules, regulations, privacy policy, and Terms of Use for
              access or usage of the domain name https://www.softetsolutions.com
              (hereinafter referred to as 'Platform').
            </p>

            <ol className="list-decimal list-inside space-y-3">
              <li>
                The Platform is owned by Softet Solutions, a company
                incorporated as sole proprietorship, with its registered office
                at Vivekanand Colony, Jagatgunj, Varanasi, Uttar Pradesh
                (hereinafter referred to as 'Platform Owner', 'we', 'us',
                'our').
              </li>
              <li>
                Your use of the Platform, services, and tools is governed by
                these Terms of Use, including applicable policies incorporated
                by reference. By using the Platform, you agree to these Terms.
              </li>
              <li>
                Any additional or conflicting terms proposed by you are
                expressly rejected and have no force or effect.
              </li>
              <li>
                The Terms of Use may be modified at any time without prior
                notice. You are responsible for reviewing them periodically to
                stay informed of updates.
              </li>
              <li>
                For the purpose of these Terms, 'you', 'your', or 'user' refers
                to any natural or legal person who agrees to become a user/buyer
                on the Platform.
              </li>
              <li>
                Accessing, browsing, or using the Platform indicates your
                agreement to all the Terms and Conditions.
              </li>
              <li>
                To use the Services, you must provide true, accurate, and
                complete information during registration and ensure proper use
                of your account.
              </li>
              <li>
                We make no warranties or guarantees regarding the accuracy,
                completeness, or suitability of information or materials on the
                Platform. You acknowledge that such information may contain
                inaccuracies or errors, and we expressly exclude liability to
                the fullest extent permitted by law.
              </li>
              <li>
                Use of the Platform and Services is at your sole risk. You are
                required to independently assess and ensure that the Services
                meet your requirements.
              </li>
              <li>
                All contents on the Platform, including design, layout,
                graphics, and materials, are proprietary and licensed to us. You
                will not claim any intellectual property rights or ownership
                over them.
              </li>
              <li>
                Unauthorized use of the Platform or Services may lead to legal
                action as per applicable laws.
              </li>
              <li>
                You agree to pay any charges associated with availing the
                Services.
              </li>
              <li>
                You must not use the Platform or Services for unlawful, illegal,
                or prohibited purposes.
              </li>
              <li>
                The Platform may contain links to third-party websites.
                Accessing these links is at your own risk and governed by the
                respective third-party terms and policies.
              </li>
              <li>
                Initiating a transaction constitutes a legally binding contract
                with the Platform Owner.
              </li>
              <li>
                You shall indemnify and hold harmless the Platform Owner, its
                affiliates, officers, directors, agents, and employees from any
                claims or penalties arising from your violation of these Terms
                or applicable laws.
              </li>
              <li>
                The parties are not liable for failure to perform obligations
                due to force majeure events.
              </li>
              <li>
                These Terms are governed by the laws of India. All disputes are
                subject to the exclusive jurisdiction of the courts in India.
              </li>
              <li>
                Any concerns or communications regarding these Terms must be
                directed to the contact information provided on the Platform.
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Term;
